layout_spectrum: 0.07965853
color:
  saturation: 0.697993
  lightness: 0.8382297
  brandStrength: 0.4580224
  brandColors:
    - '#0C0404'
    - '#534230'
    - '#FFFFFF'
    - '#91A3A2'
    - '#E1881F'
  rhythmicContrast: 0.8416255
typography_spectrum: 0.8629992
name: AAAcarDeals.com
