collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8629992
color:
  saturation: 0.7583955
  brandStrength: 0.4580224
  lightness: 0.7066231
  brandColors:
    - '#1F201B'
    - '#FFFFFF'
    - '#51402E'
    - '#A2B5B3'
    - '#825F49'
  rhythmicContrast: 0.6781716
layout_spectrum: 0.3829291
name: AAAcarDeals.com
